### ISSUE TITLE
Any need to review max number of queries or cooldown time?

### ISSUE THREAD

**Issue by alfredtangsw** [woctezuma/download-steam-reviews#12]
As mentioned in #11, I am on v0.8.2 and am trying to get reviews for appid 730.

I suspect that the query may be breaking out of the function before it reaches the date threshold, for reasons I'm unable to ascertain.

I was able to get reviews only up to 29 June (2 days ago), and it wasn't all of the reviews for the past 2 days (about 40,000). I was looking for reviews for the past 30 days, in all languages, but was unsuccessful.

The ideal solution is probably to wait until the Steam Summer Sale is over, of course. I will try that if need be, but I also tried my hand at modifying the querying functions to suit my needs (I'm a little pressed for time) with limited success. 

I am now wondering if it would help to review the max number of queries before the 310-second cooldown, or the cooldown time itself. What do you think about this?

--------------
**Details**

I just upgraded to 0.8.2 and tried out these parameters a few minutes ago (1 Jul 2019 my time) on appid 730:
```python
request_params['filter'] = 'recent'
request_params['language'] = 'all'
request_params['day_range'] = '30'
```

I only got 14,975 reviews although there are 81,273 reviews in all languages.

![image](https://user-images.githubusercontent.com/48082063/60399420-86c57d00-9b96-11e9-988d-22cfe9173ddb.png)

![image](https://user-images.githubusercontent.com/48082063/60399448-fe93a780-9b96-11e9-9d28-00c559fdf7d4.png)

**Comment by alfredtangsw** [comment]
Hmm. I wonder if I'm doing something wrong. Related to #9.

I am using my modified version of your code to deal with bad gateways, and I'm now consistently getting 4100 reviews, always ending at the same date and time of 2018-06-30 12:28.81. I did not change anything related to the thresholds, though.

I also get a lot more reviews using "updated" than "recent.

I used the following parameters on appid 730:

request_params['filter'] = 'recent'
request_params['language'] = 'all'
request_params['day_range'] = '30'

This resulted in 4100 reviews consistently, but this was not within the day range I requested. 

Strangely, I get more reviews (14,000+) when using 'updated'. However, this is also up until 30 June only.  I'm a bit lost now as to what solutions are available. Could you help me, please?

**Comment by woctezuma** [comment]
> I also get a lot more reviews using "updated" than "recent.

I believe this is normal:
- "recent" is for reviews first posted during the time window,
- "updated" is for reviews edited during the time window.

So I think "updated" should contain all the reviews returned by "recent", and usually a bit more.

**Comment by woctezuma** [comment]
> I am now wondering if it would help to review the max number of queries before the 310-second cooldown, or the cooldown time itself. What do you think about this?

Rate limits of Steam API are not documented. It is possible that they were changed, either temporarily during the summer sales, or definitely.

To have a better idea of what is going on, there are a few possibilities:
- check if there is an error message, or a warning about a faulty status code,
- check whether this issue happens with other games which have fewer reviews than CS:GO,
- try stricter values for the rate limits (fewer number of queries, or longer cooldown).

From what I understand, the issue was not introduced in v0.8.2.

**Comment by alfredtangsw** [comment]
Yup, it happened in v0.8.1 as well. 

I'll be running a few queries today with my version of your code to see if it works. (I also reduced the number of days to query to make it run faster.)

I added status reporting lines so that the user can see what type of error occurred that led to the program breaking out of the loops. 

I suggest making the package report status in a more verbose manner because the status information is useful for troubleshooting. 

My initial test run has already told me that I am getting redundant reviews, which is why it's breaking before it reaches the date threshold.

Will do more testing and get back to you later in the day. :)

**Comment by alfredtangsw** [comment]
Seems that the query works pretty well right now. I checked the dates; the reviews go back as far as we expect them to (7 days' worth of reviews). The numbers seem correct as well; I got ~58k out of ~60k reviews for the past 7 days.

Based on the evidence so far, I think it's Steam throttling query traffic over the weekend because of high levels of activity, so most likely, you did not introduce a bug.

(I still recommend having a more verbose report for the query though!)

**Comment by alfredtangsw** [comment]
Hmm, I will correct myself here. I ended up with very few reviews again, going back less than 12 hours before it downloads reviews with full redundancy. Maybe I am making too many queries in a short time?

**Comment by woctezuma** [comment]
> The numbers seem correct as well; I got ~58k out of ~60k reviews for the past 7 days.
>
> Hmm, I will correct myself here. I ended up with very few reviews again, going back less than 12 hours before it downloads reviews with full redundancy.

So you did not get ~58k reviews out of ~60k? Or was the issue with a longer time window, i.e. more than 7 days?

**Comment by woctezuma** [comment]
> I added status reporting lines so that the user can see what type of error occurred that led to the program breaking out of the loops.
>
> I suggest making the package report status in a more verbose manner because the status information is useful for troubleshooting.

Right.

**Comment by alfredtangsw** [comment]
To answer your question, I got 58k reviews but it wasn't quite all the reviews for 7 days. Maybe I confused myself downloading so many files. 

I am now testing it on Dota Underlords. So far, it got me most of the reviews for the correct time period. I will test a few more times to ascertain whether it is a problem that is isolated to CS GO.

**Comment by alfredtangsw** [comment]
I have good news. My modified code seems to work perfectly well for Dota Underlords.

![image](https://user-images.githubusercontent.com/48082063/60417122-28d67b00-9c12-11e9-8dc8-2f5a78f36b45.png)

![image](https://user-images.githubusercontent.com/48082063/60417170-4e638480-9c12-11e9-8437-661d3d74ac22.png)

![image](https://user-images.githubusercontent.com/48082063/60417575-5a037b00-9c13-11e9-9134-b7a390d8e1b6.png)

It goes back to the release date so it looks like it isn't buggy. Maybe there are a lot of people accessing CS GO, which makes it hard to scrape reviews accurately... I guess we will not know the exact reason because there is no documentation or announcement about that.

**Comment by woctezuma** [comment]
I have added a verbosity flag in v0.8.3. I will close the issue for now.

**Comment by alfredtangsw** [comment]
Hey @woctezuma thank you for the quick update. I just tested 0.8.4 on DotA 2, getting reviews from all languages for the past 30 days.

I think it is safe to say that the new version works well. I got 22157 out of 22289 reviews, going back up to 2nd April. :)

Will update you again if anything comes up. Thanks so much!

**Comment by woctezuma** [comment]
Thank you for the feedback!
