### ISSUE TITLE
Review language parameter on the get_review functions don't work as intended

### ISSUE THREAD

**Issue by torivor** [woctezuma/download-steam-reviews#26]
Thank you for simplifying the process of scraping steam reviews. Unfortunately, it seems that the review language parameter on the download_reviews function don't work as shown in the documentation. After I run the following code:

```
import steamreviews
request_params = dict()

# Reference: https://partner.steamgames.com/doc/store/localization#supported_languages
request_params['language'] = 'english'
request_params['num_per_page'] = 100

app_id = 1562430
raw_data, query_count = steamreviews.download_reviews_for_app_id(app_id, chosen_request_params = request_params, verbose=True)
raw_reviews_data_dict = raw_data["reviews"]

import pandas as pd

raw_reviews_data_df = pd.DataFrame(raw_reviews_data_dict).T
raw_reviews_data_df.head(5)
```

I found out that there are still languages outside of english (e.g. schinese) that got mixed up in the query/scraping result. Is there any solution? Thank you once again

**Comment by woctezuma** [comment]
The language of a review is not something automatically detected by Steam, **it is set by the reviewer**.
So it can happen that the reviewer writes their review in a language other than the one which they have selected.

For instance, here is a review in English as seen from the reviewer:

![English review](https://i.imgur.com/ZA3VFSX.png)

The drop-down menu allows to select other languages, even though the review is in English:

![Drop-down menu](https://i.imgur.com/mXh9gZD.png)

What I would suggest is to filter the reviews with a language detection tool. You could get rid of ASCII art as well in the process.
I would suggest these two:
- [`langdetect`](https://github.com/Mimino666/langdetect) (very basic, but it can do the job)
- [`explosion/spaCy`](https://github.com/explosion/spaCy) (updated more frequently)

Maybe you can use other tools based on spaCy, e.g. a quick-search gives [`spacy-language-detection`](https://github.com/davebulaval/spacy-language-detection) (not tested by myself, so use at your own risk).

**Comment by torivor** [comment]
Thanks for the recommendation!

However, what I'm referring to is the query results. From what I understand, it seemed that the selected option from the drop-down menu would be recorded as the value on the "language" column of the query results. Thus, by specifying the value of the review language parameter, we can choose to query only reviews with the specified language on the "language" column of the query results.

However, the query keeps returning results with non-English language regardless of the value of the review language parameter, for example:
![image](https://user-images.githubusercontent.com/59689052/229410529-63806dc7-19da-40f6-b558-9f78bda9e31e.png)

Would this be an intended behavior for the download reviews function?

**Comment by torivor** [comment]
Update:
It seemed that the mistake is on my end. I was neglectful enough to forget deleting the previous query result (without the specified review language parameter). After re-doing the query in an empty directory, it resulted into a query full of reviews with "english" as the recorded value on the language column. Thus, the issue should be closed by now. I will update any more issues should I happen to encounter any of them again. Thank you for the follow up!

**Comment by woctezuma** [comment]
Thank you for the feedback! I am glad you could figure it out!
