### ISSUE TITLE
A couple of issues. Need help.

### ISSUE THREAD

**Issue by gric69** [woctezuma/download-steam-reviews#7]
Hi Woctezuma, 
I encountered a couple of issues:
First, I changed language to: 'english' and filter: 'all' then I changed the cooldown time to 5 seconds.
The issue I faced that I think it might not have anything to do with the cooldown time is that is that the package does not download all the english reviews for an app. For example, consider this msg (it only downloads 40, but it should download 63:
"Downloading reviews for appID = 586110
[appID = 586110] expected #reviews = 63
[appID = 586110] num_reviews = 40 (expected: 63)"

This happens quit often especially when I put lists of 500 apps in the bracket and leave it to run. Could you help? what is wrong? I am using python 3.7.2

The second issue is that it when I download reviews for big apps like DOTA2 or Team Fortress2 it will run for 5 hours then produces an error (even with reduced cooldown time) maybe you can help with this.

**Comment by woctezuma** [comment]
Hi Gric69,

For your issue with the number of reviews, I believe this happens because some reviews are hidden (and therefore cannot be downloaded). For instance, reviews can be:

- flagged as abusive by the developer,
- or hidden by the reviewer so that only their friends can read the review.

![hidden reviews](https://i.imgur.com/PgRaL56.png)

So, the expected number of reviews is the total number of reviews which exist, but `num_reviews` is the total number of _visible_ reviews. You could try to check via your web-browser whether you can read the missing reviews on the Steam store ; I believe they won't be visible.

For your second issue, which error is it?

**Comment by woctezuma** [comment]
As for your changes to the `filter` value, you should be able to download all the reviews with `'filter': 'recent'`. It is just a sorting order, there is no need to change the value to `'filter': 'all'`. The code relies on an offset value to get all the reviews, and [the offset value should be used with](https://partner.steamgames.com/doc/store/getreviews) either `'filter': 'recent` or `'filter': 'updated`. With `'filter': 'all'`, you might get duplicate reviews.

**Comment by woctezuma** [comment]
As for your change to the cooldown, I am not sure I understand your change, I guess you have replaced
` 'cooldown': (5 * 60) + 10, # 5 minutes plus a cushion`
with
` 'cooldown': (5 * 60) + 5,`

If so, it is fine. Otherwise, you risk to be unable to download reviews if you have changed it to 5 seconds:
` 'cooldown': 5,`

**Comment by woctezuma** [comment]
For your second issue, which error is it?

I have checked and there are 382947 English reviews for [Dota2](https://store.steampowered.com/app/570/Dota_2/). With a rate-limit of 10 reviews per second, you would need 10 hours and 39 minutes to download them all. This makes it hard to test and find out the cause of the error.

Moreover, it is such an extreme case that it would be better to save the results to the disk quite often. You could do that by modifying `download_reviews_for_app_id()`. You would copy lines from [199](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L199) to [205](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L205) inside the [cooldown loop](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L190) and reset `new_reviews = []`. The pro is that you would have a JSON file when the error arises, so the 5 hours are not lost. The con is that there is no good way to resume the download afterwards and update the JSON file, because the check at [line 196](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L196) becomes irrelevant.

**Comment by gric69** [comment]
Thank you so much for such a quick response. I have tried to send you an email (the one provided in your license) a month ago but I couldn't reach you. I really needed your help. I have shed tears and blood for learning basic python collecting this data. Actually this is for my dissertation (it is about players immersion in games), I have no intention to use such data for anything other than scientific purposes. 

1. I checked and you are write the weird numbers that I was receiving was from changing filter to all instead of recent. Thank you!

2. I am noob. I changed the cooldown to:
'cooldown': 5,
Why is there a chance that I won't be able to download? I did some rough estimation and figured that the number of quarries even with cooldown: 5 or cooldown:10 would not reach 100,000 calls per day which is the limitation of the steam right? 
I feel bad now because it seems that I have done something retarded by changing it to 5 or 10  and it seems I have missed a big point there, I hope I have not messed up things.

3. Should it look like this (I copy pasted, not cut and paste right?)?
        if query_count >= rate_limits['max_num_queries']:
            cooldown_duration = rate_limits['cooldown']
            print('Number of queries {} reached. Cooldown: {} seconds'.format(query_count, cooldown_duration))
            time.sleep(cooldown_duration)
            query_count = 0

            for review in new_reviews:
                review_id = review['recommendationid']
                if review_id not in previous_review_ids:
                review_dict['reviews'][review_id] = review

            with open(get_output_filename(app_id), 'w') as f:
            f.write(json.dumps(review_dict) + '\n')

** I will write my feedback after testing this.

4. I will probably face errors for collecting data from big games like DOTA2 etc. I will write my feedback on this regarding your last suggestion about removing line 196-197 and setting offset.

This is my plan in theory, maybe you can help 
For example if it broke in after 100 lines of saying:
150 queries reached cooldown ---> That means Python collected 100*150*10=150,000 reviews. So the offset for continuing the process will be 150,000 / 20 = 750 
Again I know if people have added 15 reviews in between my data collection there is a chance that I miss some reviews which is fine. In general missing a percentage of reviews would not affect the statistical inferences I am gonna make about psychological behavior and intentions of games.

Looking forward to your suggestions.

**Comment by woctezuma** [comment]
Regarding the cooldown (point #2 in your post), I don't know the exact rate-limit to query reviews with Steam API, so you might be right. However, in my experience, when the cooldown was significantly lower than the value used in my code (5 minutes), then I would get temporarily banned from using the Steam API, and every query would return an error message instead of the review data.

**Comment by woctezuma** [comment]
Regarding point n°4, unless we know the error which is returned, it is difficult to say anything. If you follow my suggestion for collecting reviews for these hugely popular games, then you should at least be able to keep what was scraped and not lose everything if an error arises. If you have a JSON file for 5 hours of scraping Dota2's reviews, make sure you make a backup of it before trying to edit it or merge it with another JSON file obtained by scraping Dota2's reviews on another day.

**Comment by woctezuma** [comment]
Each query is expected to returns 20 reviews. When the maximum number of queries (150) is reached, the script waits for a cooldown duration (5 minutes and 10 seconds) before it resumes querying data. On average, that is roughly 10 reviews per second.

So, you should have 3,000 reviews (not 100,000). The offset should be equal to the number of reviews scrapped so far, so 3000 in this case.

If you want to merge data scrapped on different days, make sure that you check the field `recommendationid` in the JSON data (cf. [this check](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L196)) to avoid inserting duplicates of reviews.

**Comment by woctezuma** [comment]
It is okay.

**Comment by gric69** [comment]
Hi Woctezuma. I have collected almost all English reviews except for the first 200 most downloaded games that have have a lot of reviews like 20k+ or 40k+. 
This is one of the common errors that I sometimes encounter in the middle of download:
Traceback (most recent call last):
  ```
File "C:/Users/abalapou/AppData/Local/Programs/Python/Python37-32/Steam_ManyApps_2000k_5000k_101_150.py", line 4, in <module>
    steamreviews.download_reviews_for_app_id_batch(app_ids)
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steamreviews-0.4.1-py3.7.egg\steamreviews\download_reviews.py", line 230, in download_reviews_for_app_id_batch
    review_dict, query_count = download_reviews_for_app_id(app_id, query_count)
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steamreviews-0.4.1-py3.7.egg\steamreviews\download_reviews.py", line 173, in download_reviews_for_app_id
    success_flag, downloaded_reviews, query_summary = download_reviews_for_app_id_with_offset(app_id, offset)
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steamreviews-0.4.1-py3.7.egg\steamreviews\download_reviews.py", line 145, in download_reviews_for_app_id_with_offset
    result = resp_data.json()
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\abalapou\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Typically I would reset and re-download the reviews for that specific app if I receive this error, however, if the number of reviews is big (50k , 100k, or even 300k like DOTA2) this process is very painful because there is a chance for it to happen again.

I am gonna retry one more time then I will implement the "saving" code that you have provided by creating the loop. 

Also one update. I have used 3 computers with each using the cooldown of 10 seconds after each 150 queries and it worked very well. I don't know if it is needed change the cooldown back to 310 seconds or not.

I have have two questions:
1. How can I handle that error?
2. If I use that loop and save whatever reviews returned before the error, how can I find the "Offset" value from the 'json' file or from the code to reset it manually with a starting Offset value??

**Comment by gric69** [comment]
Hi Woctezuma,
Finally time allowed me to download the remaining reviews for the big games. 
So I added the things that you have suggested, but the program stops after the first cooldown. The modified code is as follows:
`# Objective: download every Steam review for the games of your choice.
#
# Input:
#   - idlist.txt
#
# Output:
#   - idprocessed.txt
#   - data/review_APPID.json for each APPID in idlist.txt
#
# Reference:
#   https://raw.githubusercontent.com/CraigKelly/steam-data/master/data/games.py

import json
import pathlib
import time

import requests


def parse_app_id(app_id):
    # Objective: return an app_id as an integer, no matter whether the input app_id is a string or an integer.
    try:
        return int(str(app_id).strip())
    except ValueError:
        return None


def get_input_app_ids_filename():
    # Objective: return the filename where input app_ids are stored.
    return 'idlist.txt'


def app_id_reader(filename=None):
    # Objective: return a generator of the app_ids to process.

    if filename is None:
        filename = get_input_app_ids_filename()

    with open(filename, 'r') as f:
        for row in f.readlines():
            yield parse_app_id(row)


def get_processed_app_ids_filename(filename_root='idprocessed'):
    # Objective: return the filename where processed app_ids are saved.

    # Get current day as yyyymmdd format
    current_date = time.strftime('%Y%m%d')

    processed_app_ids_filename = filename_root + '_on_' + current_date + '.txt'

    return processed_app_ids_filename


def get_processed_app_ids():
    # Objective: return a set of all previously processed app_ids.

    processed_app_ids_filename = get_processed_app_ids_filename()

    all_app_ids = set()
    try:
        for app_id in app_id_reader(processed_app_ids_filename):
            all_app_ids.add(app_id)
    except FileNotFoundError:
        print('Creating ' + processed_app_ids_filename)
        pathlib.Path(processed_app_ids_filename).touch()
    return all_app_ids


def get_default_request_parameters():
    # Objective: return a dict of default paramters for a request to Steam API.
    #
    # Reference:
    #   https://gist.github.com/adambuczek/95906b0c899c5311daeac515f740bf33

    default_request_parameters = {
        'json': '1',
        'language': 'english',  # e.g. english or schinese or all
        'filter': 'recent',  # e.g. funny or helpful or recent
        'review_type': 'all',
        'purchase_type': 'all',
    }

    return default_request_parameters


def get_data_path():
    # Objective: return the path to the directory where reviews are stored.

    data_path = 'data/'

    # Reference of the following line: https://stackoverflow.com/a/14364249
    pathlib.Path(data_path).mkdir(parents=True, exist_ok=True)

    return data_path


def get_steam_api_url():
    # Objective: return the url of Steam API for reviews.

    return 'http://store.steampowered.com/appreviews/'


def get_steam_api_rate_limits():
    # Objective: return the rate limits of Steam API for reviews.

    rate_limits = {
        'max_num_queries': 150,
        'cooldown': (1 * 60) + 10,  # 5 minutes plus a cushion
    }

    return rate_limits


def get_output_filename(app_id):
    return get_data_path() + 'review_' + str(app_id) + '.json'


def load_review_dict(app_id):
    review_data_filename = get_output_filename(app_id)

    try:
        with open(review_data_filename, 'r', encoding='utf8') as in_json_file:
            review_dict = json.load(in_json_file)
    except FileNotFoundError:
        review_dict = dict()
        review_dict['reviews'] = dict()

    return review_dict


def get_request(app_id):
    request = dict(get_default_request_parameters())
    request['appids'] = str(app_id)

    return request


def download_reviews_for_app_id_with_offset(app_id, offset=0):
    req_data = get_request(app_id)
    req_data['start_offset'] = str(offset)

    resp_data = requests.get(get_steam_api_url() + req_data['appids'], params=req_data)

    result = resp_data.json()

    success_flag = result['success']

    try:
        downloaded_reviews = result['reviews']
        query_summary = result['query_summary']
    except KeyError:
        success_flag = False
        downloaded_reviews = []
        query_summary = dict()

    return success_flag, downloaded_reviews, query_summary


def download_reviews_for_app_id(app_id, query_count=0):
    rate_limits = get_steam_api_rate_limits()

    review_dict = load_review_dict(app_id)

    previous_review_ids = review_dict['reviews']

    num_reviews = None

    offset = 0
    new_reviews = []

    while (num_reviews is None) or (offset < num_reviews):
        success_flag, downloaded_reviews, query_summary = download_reviews_for_app_id_with_offset(app_id, offset)

        delta_reviews = len(downloaded_reviews)

        offset += delta_reviews
        print(offset)
        query_count += 1

        if success_flag and delta_reviews > 0:
            new_reviews.extend(downloaded_reviews)
        else:
            break

        if num_reviews is None:
            review_dict['query_summary'] = query_summary
            num_reviews = query_summary['total_reviews']
            print('[appID = {}] expected #reviews = {}'.format(app_id, review_dict['query_summary']['total_reviews']))

        if query_count >= rate_limits['max_num_queries']:
            cooldown_duration = rate_limits['cooldown']
            print('Number of queries {} reached. Cooldown: {} seconds'.format(query_count, cooldown_duration))
            time.sleep(cooldown_duration)
            query_count = 0
            #copied line 199-205 of the original to this section
            for review in new_reviews:
                review_id = review['recommendationid']
                if review_id not in previous_review_ids:
                    review_dict['reviews'][review_id] = review

            with open(get_output_filename(app_id), 'w') as f:
                f.write(json.dumps(review_dict) + '\n')
            #end of copy

        if any([review['recommendationid'] in previous_review_ids for review in downloaded_reviews]):
            break

    for review in new_reviews:
        review_id = review['recommendationid']
        if review_id not in previous_review_ids:
            review_dict['reviews'][review_id] = review

    with open(get_output_filename(app_id), 'w') as f:
        f.write(json.dumps(review_dict) + '\n')

    return review_dict, query_count


def download_reviews_for_app_id_batch(input_app_ids=None, previously_processed_app_ids=None):
    if input_app_ids is None:
        print('Loading {}'.format(get_input_app_ids_filename()))
        input_app_ids = [app_id for app_id in app_id_reader()]

    if previously_processed_app_ids is None:
        print('Loading {}'.format(get_processed_app_ids_filename()))
        previously_processed_app_ids = get_processed_app_ids()

    query_count = 0
    game_count = 0

    for app_id in input_app_ids:

        if app_id in previously_processed_app_ids:
            print('Skipping previously found appID = {}'.format(app_id))
            continue
        else:
            print('Downloading reviews for appID = {}'.format(app_id))

        review_dict, query_count = download_reviews_for_app_id(app_id, query_count)

        game_count += 1

        with open(get_processed_app_ids_filename(), 'a') as f:
            f.write(str(app_id) + '\n')

        print('[appID = {}] num_reviews = {} (expected: {})'.format(app_id, len(review_dict['reviews']),
                                                                    review_dict['query_summary']['total_reviews']))

    print('Game records written: {}'.format(game_count))

    return True


if __name__ == '__main__':
    # noinspection PyTypeChecker
    download_reviews_for_app_id_batch(input_app_ids=None, previously_processed_app_ids=None)
`

and this is my python shell:
`Loading idprocessed_on_20190312.txt
Creating idprocessed_on_20190312.txt
Downloading reviews for appID = 570
20
[appID = 570] expected #reviews = 386753
40
60
80
100
120
140
160
180
200
220
240
260
280
299
319
339
359
379
399
419
439
459
479
499
519
539
559
579
599
619
639
659
679
699
719
739
759
779
799
819
839
859
879
899
919
939
959
979
999
1019
1039
1059
1079
1099
1119
1139
1159
1179
1199
1219
1239
1259
1279
1299
1319
1339
1359
1379
1399
1419
1439
1459
1479
1499
1519
1539
1559
1579
1599
1619
1639
1659
1679
1699
1719
1739
1759
1779
1799
1819
1839
1859
1879
1899
1919
1939
1959
1979
1999
2019
2039
2059
2079
2099
2119
2139
2159
2179
2199
2219
2239
2259
2279
2299
2319
2339
2359
2379
2399
2419
2439
2459
2479
2499
2519
2539
2559
2579
2599
2619
2639
2659
2679
2699
2719
2739
2759
2779
2799
2819
2839
2859
2879
2899
2919
2939
2959
2979
2999
Number of queries 150 reached. Cooldown: 70 seconds
[appID = 570] num_reviews = 2741 (expected: 386753)
Game records written: 1
>>> `

**Comment by gric69** [comment]
Ok, I have to try and fix the code up there, apparently it failed to copy-paste it in the right format.

**Comment by gric69** [comment]
I had no other way but to copy it in JPG format. 

Basically my shell stops after the first Cooldown. I have tried to set the Cooldown to 70 seconds for big reviews. I might change it back to 10s like last time, but more importantly, What I don't understand is: Why it stops after reaching the first cooldown?

Could you please share your opinion on this?

**Comment by woctezuma** [comment]
If the program stops after the first cooldown, then it has to be due to [`break`](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L197). You could:
- either make sure you start without any file called `data/review_570.json`,
- or replace `break` with `pass` so that the program does not stop there, but there is a risk that the program would not terminate at all.

Moreover, for better performance, I would suggest:
- to add [this line](https://github.com/woctezuma/download-steam-reviews/blob/f162b899f4f157ae4c1e3ebe1c72076e264f950d/steamreviews/download_reviews.py#L84) to be able to dowload 100 reviews instead of 20 per query,
- to reset new_reviews as mentioned [here](https://github.com/woctezuma/download-steam-reviews/issues/7#issuecomment-453629495).

**Comment by gric69** [comment]
Thank you, I will change from 20 to 100. If I replace break with pass wouldn't the program run forever? 

Furthermore, I am not quiet sure how should I reset `new_reviews = []` 
Could you please guide me how to do that?

**Comment by woctezuma** [comment]
> Thank you, I will change from 20 to 100. If I replace break with pass wouldn't the program run forever?

No, the program can stop with this other [`break`](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L183).

The purpose of the [`break`](https://github.com/woctezuma/download-steam-reviews/blob/ff0453aa8dc83f8012074421b1966815d56f4c54/steamreviews/download_reviews.py#L197) which I suggested to remove is to be able to resume the download of reviews for a game.

> Furthermore, I am not quiet sure how should I reset new_reviews = []
> Could you please guide me how to do that?

As for resetting the variable `new_reviews`, it is in the same location which you previously modified, just copy and paste as described [here](https://github.com/woctezuma/download-steam-reviews/issues/7#issuecomment-453629495).

**Comment by gric69** [comment]
Hi thanks for your quick response,

> As for resetting the variable new_reviews, it is in the same location which you previously modified, just copy and paste as described here.

Yes I have already implemented this code as advised, but this was the cause of the break before after the first cooldown.  I was thinking that by "reset" you mean that I have to add something else to [https://github.com/woctezuma/download-steam-reviews/issues/7#issuecomment-453629495](url) 

On the JPG file if the whole source code that I submitted the code apepars on the line 197 on which I have puted a note: 
`copied line 199-205 from original code ....`

**Comment by woctezuma** [comment]
Yes, that is what I mentioned [here](https://github.com/woctezuma/download-steam-reviews/issues/7#issuecomment-453457861). The first bullet point is to copy lines 199-205 inside the loop, as you did. The second bullet point is to add `new_reviews = []` just after the copy-paste, with the same indentation. In the end, it would look like [this](https://github.com/woctezuma/download-steam-reviews/issues/7#issuecomment-453629495).

**Comment by gric69** [comment]
Oh! I see it now. I am missing a line which is 'new_reviews = []'.
